kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Volumes/projects/pixelml/
    containerPath: /local/projects/pixelml
    readOnly: false
    selinuxRelabel: false
    propagation: None