---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfx-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/local/projects/pixelml"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tfx-pvc
  namespace: kubeflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  volumeName: tfx-pv
  resources:
    requests:
      storage: 500Mi