FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:bullseye


# RUN ENABLE_NONROOT_DOCKER=false \
#     /bin/bash \
#     -c "$(curl -fsSL https://raw.githubusercontent.com/devcontainers/features/main/src/docker-outside-of-docker/install.sh)"
